apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: web-api
        image: julio456ACR.azurecr.io/webapi:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 125m
          limits:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-api
